# Generated by Django 4.0.5 on 2022-06-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('activities', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('pricepn', models.FloatField()),
                ('nreservas', models.IntegerField()),
                ('nvagas', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='parque_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.DateField()),
                ('datef', models.DateField()),
                ('activity', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parque')),
            ],
        ),
    ]
