# Generated by Django 4.0.5 on 2022-06-07 23:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('rating', models.IntegerField()),
                ('pricepn', models.IntegerField()),
                ('nreservas', models.IntegerField()),
                ('nvagas', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='parques_pics')),
            ],
        ),
    ]
