# Generated by Django 4.0.5 on 2022-06-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('atv1', models.CharField(max_length=100)),
                ('atv2', models.CharField(max_length=100)),
                ('atv3', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('pricepn', models.IntegerField()),
                ('nreservas', models.IntegerField()),
                ('nvagas', models.IntegerField()),
            ],
        ),
    ]
