# Generated by Django 4.0.5 on 2022-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='npessoas',
            field=models.IntegerField(default=1),
        ),
    ]
