# Generated by Django 4.0.5 on 2022-06-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atvs', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parques',
            name='atv1',
        ),
        migrations.RemoveField(
            model_name='parques',
            name='atv2',
        ),
        migrations.RemoveField(
            model_name='parques',
            name='atv3',
        ),
        migrations.AddField(
            model_name='parques',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='parques',
            name='activities',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.atividades'),
            preserve_default=False,
        ),
    ]
