# Generated by Django 4.0.5 on 2022-06-07 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_parques_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parques',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None),
        ),
        migrations.DeleteModel(
            name='Atividades',
        ),
    ]
